# Generated by Django 4.2.29 on 2026-04-04 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('turmas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fim', models.TimeField(blank=True, null=True)),
                ('escopo', models.CharField(choices=[('GERAL', 'Geral'), ('TURMA', 'Turma')], default='GERAL', max_length=5)),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Baixa'), ('NORMAL', 'Normal'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='NORMAL', max_length=7)),
                ('local_evento', models.CharField(blank=True, max_length=150, null=True)),
                ('publico', models.CharField(choices=[('PAIS', 'Pais'), ('PROFESSORES', 'Professores'), ('TODOS', 'Todos')], default='TODOS', max_length=11)),
                ('publicado', models.BooleanField(default=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'eventos',
                'ordering': ['data_inicio', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='TipoEvento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('cor', models.CharField(blank=True, max_length=20, null=True)),
                ('icone', models.CharField(blank=True, max_length=50, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tipos_evento',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='EventoTurma',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('evento', models.ForeignKey(db_column='evento_id', on_delete=django.db.models.deletion.CASCADE, related_name='eventos_turmas', to='eventos.evento')),
                ('turma', models.ForeignKey(db_column='turma_id', on_delete=django.db.models.deletion.CASCADE, related_name='eventos_turmas', to='turmas.turma')),
            ],
            options={
                'db_table': 'eventos_turmas',
            },
        ),
    ]
