# Generated by Django 4.2.29 on 2026-04-04 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('turmas', '0001_initial'),
        ('eventos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='criado_por',
            field=models.ForeignKey(db_column='criado_por', on_delete=django.db.models.deletion.RESTRICT, related_name='eventos_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evento',
            name='tipo_evento',
            field=models.ForeignKey(db_column='tipo_evento_id', db_index=False, on_delete=django.db.models.deletion.RESTRICT, related_name='eventos', to='eventos.tipoevento'),
        ),
        migrations.AddField(
            model_name='evento',
            name='turmas',
            field=models.ManyToManyField(blank=True, related_name='eventos', through='eventos.EventoTurma', to='turmas.turma'),
        ),
        migrations.AddConstraint(
            model_name='eventoturma',
            constraint=models.UniqueConstraint(fields=('evento', 'turma'), name='uq_evento_turma'),
        ),
        migrations.AddIndex(
            model_name='evento',
            index=models.Index(fields=['data_inicio'], name='idx_eventos_data_inicio'),
        ),
        migrations.AddIndex(
            model_name='evento',
            index=models.Index(fields=['tipo_evento'], name='idx_eventos_tipo'),
        ),
        migrations.AddIndex(
            model_name='evento',
            index=models.Index(fields=['publicado'], name='idx_eventos_publicado'),
        ),
    ]
