# Generated by Django 4.2.29 on 2026-04-04 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=100)),
                ('tabela_afetada', models.CharField(blank=True, max_length=100, null=True)),
                ('registro_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('ip_origem', models.CharField(blank=True, max_length=45, null=True)),
                ('data_acao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'logs_sistema',
                'ordering': ['-data_acao'],
            },
        ),
    ]
