# Generated by Django 4.2.29 on 2026-04-04 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('turmas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('mensagem', models.TextField()),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
                ('data_expiracao', models.DateTimeField(blank=True, null=True)),
                ('escopo', models.CharField(choices=[('GERAL', 'Geral'), ('TURMA', 'Turma')], default='GERAL', max_length=5)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'avisos',
                'ordering': ['-data_publicacao'],
            },
        ),
        migrations.CreateModel(
            name='AvisoTurma',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('aviso', models.ForeignKey(db_column='aviso_id', on_delete=django.db.models.deletion.CASCADE, related_name='avisos_turmas', to='avisos.aviso')),
                ('turma', models.ForeignKey(db_column='turma_id', on_delete=django.db.models.deletion.CASCADE, related_name='avisos_turmas', to='turmas.turma')),
            ],
            options={
                'db_table': 'avisos_turmas',
            },
        ),
    ]
