# Generated by Django 4.2.29 on 2026-04-04 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('turmas', '0001_initial'),
        ('avisos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aviso',
            name='publicado_por',
            field=models.ForeignKey(db_column='publicado_por', on_delete=django.db.models.deletion.RESTRICT, related_name='avisos_publicados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aviso',
            name='turmas',
            field=models.ManyToManyField(blank=True, related_name='avisos', through='avisos.AvisoTurma', to='turmas.turma'),
        ),
        migrations.AddConstraint(
            model_name='avisoturma',
            constraint=models.UniqueConstraint(fields=('aviso', 'turma'), name='uq_aviso_turma'),
        ),
        migrations.AddIndex(
            model_name='aviso',
            index=models.Index(fields=['data_publicacao'], name='idx_avisos_publicacao'),
        ),
    ]
