# Generated by Django 4.2.29 on 2026-04-04 19:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('turmas', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('password', models.CharField(db_column='senha', max_length=255)),
                ('tipo_usuario', models.CharField(choices=[('ADMIN', 'Admin'), ('DIRETOR', 'Diretor'), ('PROFESSOR', 'Professor'), ('RESPONSAVEL', 'Responsável')], max_length=12)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^[0-9()+\\-\\s]*$', 'Telefone inválido.')])),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'usuarios',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ResponsavelAluno',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('parentesco', models.CharField(blank=True, max_length=50, null=True)),
                ('responsavel_principal', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(db_column='aluno_id', on_delete=django.db.models.deletion.CASCADE, related_name='responsaveis', to='turmas.aluno')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_alunos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'responsaveis_alunos',
                'ordering': ['-responsavel_principal', 'usuario__nome'],
            },
        ),
        migrations.AddConstraint(
            model_name='responsavelaluno',
            constraint=models.UniqueConstraint(fields=('usuario', 'aluno'), name='uq_responsavel_aluno'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['tipo_usuario'], name='idx_usuarios_tipo'),
        ),
    ]
