# Generated by Django 4.2.29 on 2026-04-04 19:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnoLetivo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ano', models.PositiveSmallIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1901), django.core.validators.MaxValueValidator(2155)])),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'anos_letivos',
                'ordering': ['-ano'],
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome_turma', models.CharField(max_length=100)),
                ('serie', models.CharField(max_length=50)),
                ('segmento', models.CharField(blank=True, max_length=50, null=True)),
                ('turno', models.CharField(blank=True, max_length=30, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('ano_letivo', models.ForeignKey(db_column='ano_letivo_id', on_delete=django.db.models.deletion.RESTRICT, related_name='turmas', to='turmas.anoletivo')),
            ],
            options={
                'db_table': 'turmas',
                'ordering': ['ano_letivo__ano', 'serie', 'nome_turma'],
            },
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('matricula', models.CharField(max_length=50, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('turma', models.ForeignKey(db_column='turma_id', db_index=False, on_delete=django.db.models.deletion.RESTRICT, related_name='alunos', to='turmas.turma')),
            ],
            options={
                'db_table': 'alunos',
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['turma'], name='idx_alunos_turma')],
            },
        ),
    ]
